### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SOLequalsVOID** [M4cs/Photocord#1]
When I run python3 photocord.py while in the Photocord directory i get this error message

Traceback (most recent call last):
  File "photocord.py", line 26, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

Keep in mind i have already downloaded the requirements by running 
pip install python-magic

Not sure whats going on here, any help would be appreciated.

**Comment by SOLequalsVOID** [comment]
By removing import magic on line 26 i was able to access the UI after running photocard.py.
after choosing option 1 i got this error message

[photocord]> 1
Traceback (most recent call last):
  File "photocord.py", line 163, in <module>
    main()
  File "photocord.py", line 152, in main
    grabArchives(lol=False)
  File "photocord.py", line 31, in grabArchives
    mag = magic.Magic(mime=True, uncompress=True)
NameError: name 'magic' is not defined

ill update this if i find anything else out

**Comment by M4cs** [comment]
Try using a virtualenv and installing your modules on there and running it though there.

**Comment by M4cs** [comment]
If you are on windows its also `python-magic-win64` from pip
